name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-web-admin:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
      - name: "Trigger jenkins job"
        uses: wei/curl@v1
        with:
          args: "-X POST -u deployer:11ba1b2e0d8f1085cf1726a5884b64d669 http://95.163.242.79:8081/job/Web/job/Admin/buildWithParameters --header 'Jenkins-Crumb: c76199d00eb013983738fc4df2450ca41c88e6850ac02850d7e1c95ac8e35f8f' --form 'FFTAG=\"${{  github.ref_name }}\"'"
